// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniAgentConsole.Infrastructure.Persistence;

#nullable disable

namespace OmniAgentConsole.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgentConsoleDbContext))]
    [Migration("20260812080909_AgentGroupsAndPanelSessions")]
    partial class AgentGroupsAndPanelSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiCredentialId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomApiUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DefaultModel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FallbackModels")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("OmniAgent");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiCredentialId");

                    b.HasIndex("Type");

                    b.ToTable("agent_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultModel = "meta/llama-3.1-8b-instruct",
                            Description = "Analyzes the user request and creates the execution plan.",
                            Enabled = true,
                            MaxTokens = 4096,
                            Name = "Planner Agent",
                            Provider = "OmniAgent",
                            RetryCount = 2,
                            SystemPrompt = "You are the planner agent. Break the task into structured steps and select agents.",
                            Temperature = 0.2m,
                            TimeoutSeconds = 120,
                            Type = "Planner"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultModel = "meta/llama-3.1-8b-instruct",
                            Description = "Analyzes provided context and extracts useful facts.",
                            Enabled = true,
                            MaxTokens = 4096,
                            Name = "Research Agent",
                            Provider = "OmniAgent",
                            RetryCount = 2,
                            SystemPrompt = "You are the research agent. Work only with supplied context in MVP mode.",
                            Temperature = 0.2m,
                            TimeoutSeconds = 120,
                            Type = "Research"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultModel = "meta/llama-3.1-8b-instruct",
                            Description = "Produces code and implementation guidance.",
                            Enabled = true,
                            MaxTokens = 4096,
                            Name = "Coder Agent",
                            Provider = "OmniAgent",
                            RetryCount = 2,
                            SystemPrompt = "You are the Coder Agent. Your job is to output full, complete, and production-ready source code files. Do not output incomplete code snippets, do not output explanations, and do not output placeholder text. Each code block you produce must represent a single, full file. At the very beginning of each code block, you MUST include a comment indicating the target relative file path, formatted exactly as follows:\n- For Go: // filepath: path/to/file.go\n- For JavaScript/TypeScript: // filepath: path/to/file.js\n- For Python: # filepath: path/to/file.py\n- For HTML: <!-- filepath: path/to/file.html -->\n- For CSS: /* filepath: path/to/file.css */\n- For JSON: \"filepath\": \"path/to/file.json\" (must be inside the main object, e.g. as the first key)\n- For Markdown: <!-- filepath: path/to/file.md -->\nIf you are generating a project, you MUST always include a comprehensive README.md file as one of the code blocks.\nIf no specific version is mentioned in the prompt, you MUST default to using the latest stable production versions of all frameworks, libraries, databases, and runtimes (e.g., Node.js, .NET, Java, Go, Python, Redis, RabbitMQ, MongoDB, PostgreSQL, etc.).\nWrite complete, runnable code files that fulfill the request.",
                            Temperature = 0.2m,
                            TimeoutSeconds = 120,
                            Type = "Coder"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultModel = "meta/llama-3.1-8b-instruct",
                            Description = "Reviews quality, safety, consistency, and missing steps.",
                            Enabled = true,
                            MaxTokens = 4096,
                            Name = "Reviewer Agent",
                            Provider = "OmniAgent",
                            RetryCount = 2,
                            SystemPrompt = "You are the reviewer agent. Find issues and provide concrete corrections.",
                            Temperature = 0.2m,
                            TimeoutSeconds = 120,
                            Type = "Reviewer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultModel = "meta/llama-3.1-8b-instruct",
                            Description = "Tracks usage, latency, failures, and task runtime metrics.",
                            Enabled = true,
                            MaxTokens = 4096,
                            Name = "Ops Monitor Agent",
                            Provider = "OmniAgent",
                            RetryCount = 2,
                            SystemPrompt = "You are the ops monitor agent. Summarize execution metrics and anomalies.",
                            Temperature = 0.2m,
                            TimeoutSeconds = 120,
                            Type = "OpsMonitor"
                        });
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentExecutionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TaskRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("TaskRunId");

                    b.ToTable("agent_execution_steps", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("agent_groups", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiCredentialId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultModel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("FallbackModels")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiCredentialId");

                    b.HasIndex("GroupId", "SortOrder");

                    b.ToTable("agent_group_members", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Input")
                        .HasColumnType("text");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TaskRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentDefinitionId");

                    b.HasIndex("TaskRunId", "ExecutionOrder");

                    b.ToTable("agent_runs", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.ApiCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ApiKeySecretKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ApiKeySecretPath")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KeyLastFour")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("api_credentials", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.ConsoleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TaskRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("TaskRunId", "CreatedAt");

                    b.ToTable("console_events", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.ModelCallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("PromptHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RawMetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TaskRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TaskRunId");

                    b.HasIndex("Provider", "Model");

                    b.ToTable("model_call_logs", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.ModelDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ContextWindow")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("SupportsChat")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsEmbeddings")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Model")
                        .IsUnique();

                    b.ToTable("model_definitions", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.ModelProviderSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeySecretName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultModel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("model_provider_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            ApiKeySecretName = "OMNIAGENT_API_KEY",
                            BaseUrl = "https://integrate.api.nvidia.com/v1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultModel = "meta/llama-3.1-8b-instruct",
                            Enabled = true,
                            Provider = "OmniAgent",
                            RetryCount = 2,
                            TimeoutSeconds = 120
                        });
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.PanelConsoleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("PanelSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PanelTurnId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("PanelTurnId");

                    b.HasIndex("PanelSessionId", "CreatedAt");

                    b.ToTable("panel_console_events", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.PanelSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("FloorDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerSessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalInputTokens")
                        .HasColumnType("integer");

                    b.Property<long>("TotalLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalOutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwnerSessionId");

                    b.HasIndex("Status");

                    b.ToTable("panel_sessions", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.PanelTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("MemberDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SessionId", "TurnOrder");

                    b.ToTable("panel_turns", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.SkillDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("skill_definitions", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.TaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("InputContextJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("InputPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerSessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<int>("TotalInputTokens")
                        .HasColumnType("integer");

                    b.Property<long>("TotalLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalOutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OwnerSessionId");

                    b.HasIndex("Status");

                    b.ToTable("task_runs", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.UsageMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("FailedRequests")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SuccessfulRequests")
                        .HasColumnType("integer");

                    b.Property<int>("TotalInputTokens")
                        .HasColumnType("integer");

                    b.Property<long>("TotalLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalOutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStart", "PeriodEnd");

                    b.ToTable("usage_metrics", (string)null);
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentDefinition", b =>
                {
                    b.HasOne("OmniAgentConsole.Domain.Entities.ApiCredential", "ApiCredential")
                        .WithMany()
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApiCredential");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentExecutionStep", b =>
                {
                    b.HasOne("OmniAgentConsole.Domain.Entities.AgentRun", "AgentRun")
                        .WithMany("ExecutionSteps")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniAgentConsole.Domain.Entities.TaskRun", "TaskRun")
                        .WithMany()
                        .HasForeignKey("TaskRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRun");

                    b.Navigation("TaskRun");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentGroupMember", b =>
                {
                    b.HasOne("OmniAgentConsole.Domain.Entities.ApiCredential", "ApiCredential")
                        .WithMany()
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniAgentConsole.Domain.Entities.AgentGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiCredential");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentRun", b =>
                {
                    b.HasOne("OmniAgentConsole.Domain.Entities.AgentDefinition", "AgentDefinition")
                        .WithMany()
                        .HasForeignKey("AgentDefinitionId");

                    b.HasOne("OmniAgentConsole.Domain.Entities.TaskRun", "TaskRun")
                        .WithMany("AgentRuns")
                        .HasForeignKey("TaskRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentDefinition");

                    b.Navigation("TaskRun");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.ConsoleEvent", b =>
                {
                    b.HasOne("OmniAgentConsole.Domain.Entities.AgentRun", "AgentRun")
                        .WithMany("ConsoleEvents")
                        .HasForeignKey("AgentRunId");

                    b.HasOne("OmniAgentConsole.Domain.Entities.TaskRun", "TaskRun")
                        .WithMany("ConsoleEvents")
                        .HasForeignKey("TaskRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRun");

                    b.Navigation("TaskRun");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.ModelCallLog", b =>
                {
                    b.HasOne("OmniAgentConsole.Domain.Entities.AgentRun", "AgentRun")
                        .WithMany("ModelCallLogs")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniAgentConsole.Domain.Entities.TaskRun", "TaskRun")
                        .WithMany("ModelCallLogs")
                        .HasForeignKey("TaskRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRun");

                    b.Navigation("TaskRun");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.PanelConsoleEvent", b =>
                {
                    b.HasOne("OmniAgentConsole.Domain.Entities.PanelSession", "PanelSession")
                        .WithMany("ConsoleEvents")
                        .HasForeignKey("PanelSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniAgentConsole.Domain.Entities.PanelTurn", "PanelTurn")
                        .WithMany()
                        .HasForeignKey("PanelTurnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PanelSession");

                    b.Navigation("PanelTurn");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.PanelSession", b =>
                {
                    b.HasOne("OmniAgentConsole.Domain.Entities.AgentGroup", "Group")
                        .WithMany("PanelSessions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.PanelTurn", b =>
                {
                    b.HasOne("OmniAgentConsole.Domain.Entities.AgentGroupMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniAgentConsole.Domain.Entities.PanelSession", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentGroup", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("PanelSessions");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.AgentRun", b =>
                {
                    b.Navigation("ConsoleEvents");

                    b.Navigation("ExecutionSteps");

                    b.Navigation("ModelCallLogs");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.PanelSession", b =>
                {
                    b.Navigation("ConsoleEvents");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("OmniAgentConsole.Domain.Entities.TaskRun", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("ConsoleEvents");

                    b.Navigation("ModelCallLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
